Step2
jhta-metoring/java-todo-list pull request #25
Opened 2024-12-22 08:41 UTC by bitnalchan92

## 🔥 ㅤPR Contents

- 학원에서 배운 내용 참고, 요구사항에 맞게 작성하려 했습니다. 

## 🛠ㅤChanges (optional)

- 1. 지난 멘토링때 피드백받은 내용 반영하여 일부 수정
- 2. 2단계 요구사항 반영

## 🙋ㅤComments (optional)

- TodoService 클래스: 비즈니스 로직을 처리합니다. Todo 데이터의 처리 과정에서 발생하는 비즈니스 규칙을 실행하며, 필요한 데이터 작업을 위해 TodoRepository에 접근합니다. => 요구사항에 작성된 내용중 이 문구가 조금 헤깔렸습니다. "비즈니스 규칙 & 로직"등 어떤 것을 예로 들을 수 있는지 궁굼합니다.

2024-12-23 08:05 UTC, lehdqlsl requested changes
코드 전반적으로 깔끔하고 가독성있게 작성 잘 하셨습니다.

우선, 거대해진 컨트롤러 코드를, service, input, output 클래스 분리해서 작성바랍니다.
그리고 null을 반환하는 코드는 지양하는게 좋습니다.

그 외 몇 가지 코멘트 남겼으니 참고바랍니다~

2024-12-23 08:05 UTC, lehdqlsl commented on src/main/java/org/homework/func/IDGenerator.java
> +}
간단하지만, 아이디어는 매우 좋았습니다.
해당 클래스는 프로그램에서 전역적으로, 고유 객체 형태로 사용되기 때문에, 싱글톤 패턴을 사용해서 객체를 생성하는 것도 좋을거같습니다~ (물론 해당 프로젝트에서는 과한 구현이긴 하지만, 참고만 바랍니다.)

2024-12-23 08:05 UTC, lehdqlsl commented on src/main/java/org/homework/repository/TodoRepository.java
> +    }
setId까지는 repository 영역이라 괜찮은데, setIsCompleted 여부는 객체 생성시점에 같이 초기화되는게 더 적합한거 같습니다~

물론 db라 가정했을때, 테이블 기본값을 '미완료'로 설정할수도 있긴합니다만, db쪽 의존성이나 비즈니스결합도를 낮추는게 더 중요해서 보통 코드레벨에서 (객체생성 등) 기본값을 셋팅합니다.

2024-12-23 08:05 UTC, lehdqlsl commented on src/main/java/org/homework/repository/TodoRepository.java
> +    }
stream 활용 👍 
그러나 null을 반환하는 코드는 외부에서 null exception을 발생시킬 여지가 있기때문에
 .findFirst() 반환만하고, 외부에서 로직을 처리하는게 더 안전합니다.

2024-12-23 08:05 UTC, lehdqlsl commented on src/main/java/org/homework/Options.java
> +    }
여기도 마찬가지로 null 반환코드 참고부탁해요.

2024-12-28 14:55 UTC, bitnalchan92 commented on src/main/java/org/homework/func/IDGenerator.java
> +}
싱글톤 패턴으로 구현하는 방법도 확인해보겠습니다!

2024-12-28 23:27 UTC, bitnalchan92 commented on src/main/java/org/homework/repository/TodoRepository.java
> +    }
피드백 내용 반영해서, Todo.java의 isCompleted 타입을 boolean으로 바꾸고, 기본값 false로 셋팅하도록 수정했습니다.

2024-12-29 00:00 UTC, bitnalchan92 commented on src/main/java/org/homework/repository/TodoRepository.java
> +    }
orElse(null) 부분을 repository -> service에서 처리하도록 옮겼습니다.

2024-12-29 00:23 UTC, bitnalchan92 commented on src/main/java/org/homework/Options.java
> +    }
예외를 던지거나, 기본 Enum요소 반환을 생각하였지만 현재 사용하지 않는 함수여서 삭제하였습니다

2024-12-29 02:48 UTC, lehdqlsl approved these changes
각 layer별로 역할이 잘 나눠지면서 코드가 매우 간결해졌습니다. 👍 
소소한 피드백 남겼으니 참고해주시고, 다음 단계 진행해주시면 되겠습니다.

2024-12-29 02:48 UTC, lehdqlsl commented on src/main/java/org/homework/controller/TodoController.java
> +                    outputView.printDoneResult(todoService.doneTodoById(todoId));
한 줄로 작성하면 깔끔해 보일 수 있지만, 문장이 길어지면 가독성이 떨어지므로 구체적인 변수명을 추출해 분리하는 것이 더 효과적입니다.

2024-12-29 02:48 UTC, lehdqlsl commented on src/main/java/org/homework/service/TodoService.java
> +        return -1;
C 언어에서는 `-1`과 같은 값을 반환해 오류를 나타내는 경우가 많지만, 자바에서는 매직 넘버를 사용하는 대신 의미를 명확히 하기 위해 상수를 정의하는 것이 권장됩니다. 

```java
public static final int ERROR_CODE = -1;
```
예외를 활용한 에러 처리는 3단계에서 진행할 예정이므로, 해당 단계에서 적절한 예외를 던지는 방식을 도입해보는 것을 추천합니다.

2024-12-29 02:48 UTC, merged